dist: xenial
os: linux

language: php

php:
  - 7.4

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - TRAVIS=1 && composer install --no-interaction --no-scripts
  - php artisan key:generate
  - nvm install 14.4.0
  - npm install npm@latest -g
  - npm install

script:
  - npm run test
  - php artisan test
