dist: trusty

language: php

php:
  - 7.4

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - nvm install 13.3.0
  - npm install npm@latest -g
  - npm install

script:
  # - php artisan test
  - vendor/bin/phpunit
  - npm run test
